GET http://localhost:3000/users



###
POST http://localhost:3000/signup
Content-Type: application/json

{
    "name": "Bobby",
    "password": "Bob777"
}



### 
POST http://localhost:3000/signin
Content-Type: application/json

{
    "name": "Bobby",
    "password": "Bob777"
}
