GET http://localhost:3000/users



###
GET http://localhost:3000/users/661984d2f1585fcd1522c365



###
POST http://localhost:3000/users
Content-Type: application/json

{
    "name": "Aziza",
    "password": "aziza777"
}


###
PATCH http://localhost:3000/users/661984d2f1585fcd1522c365
Content-Type: application/json

{
    "name": "Azishka",
    "password": "1"
}



###
DELETE http://localhost:3000/users/661984d2f1585fcd1522c365
