GET http://localhost:5000/tasks

### 

GET http://localhost:5000/tasks/661cc005f0865714a09fae2b

###

POST http://localhost:5000/tasks
Content-Type: application/json

{
    "title": "Task 1",
    "description": "Description 1"
}

###
PATCH http://localhost:5000/tasks/661cc8b6c66a589d44986f90
Content-Type:  application/json

{
    "title": "Task One",
    "description": "Description One"
}

###
DELETE http://localhost:5000/tasks/661cc11ad6c2ae3770254dc8


### 
POST http://localhost:5000/users/signup
Content-Type: application/json

{
    "username": "John",
    "email": "john@gmail.com",
    "password": "john"
}

### 
POST http://localhost:5000/users/login
Content-Type: application/json

{
    "username": "Bob",
    "password": "bob"
}

###
GET http://localhost:5000/users

###
POST http://localhost:5000/users/logout

